name: Host tests

on:
  push:
  pull_request:

jobs:
  test-suite:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Run host-based test suite
        working-directory: test
        run: ./run_tests.sh
