// versions.json is generated by installer/build-site.sh, newest release first,
// with one manifest and one firmware binary per version. ESP Web Tools reads
// the manifest when the button is clicked, so switching versions is just a
// matter of re-pointing the button's manifest attribute.
//
// Kept in its own file rather than inline so the page's Content-Security-Policy
// can be script-src 'self' with no 'unsafe-inline'.
const select = document.getElementById('version');
const installer = document.getElementById('installer');
const notes = document.getElementById('notes');
const older = document.getElementById('older');
const olderLatest = document.getElementById('older-latest');

function apply(entry, latest) {
  installer.setAttribute('manifest', './' + entry.manifest);
  notes.href = entry.notes;
  olderLatest.textContent = latest;
  older.hidden = entry.version === latest;
}

fetch('./versions.json')
  .then((r) => {
    if (!r.ok) throw new Error('versions.json: HTTP ' + r.status);
    return r.json();
  })
  .then((data) => {
    const list = data.versions || [];
    if (!list.length) throw new Error('no versions listed');

    select.textContent = '';
    for (const entry of list) {
      const opt = document.createElement('option');
      opt.value = entry.version;
      opt.textContent =
        entry.version +
        (entry.version === data.latest ? ' (latest)' : '') +
        (entry.published ? ' — ' + entry.published : '');
      select.append(opt);
    }
    select.disabled = list.length < 2;
    select.value = data.latest;
    apply(list.find((e) => e.version === data.latest) || list[0], data.latest);

    select.addEventListener('change', () => {
      const entry = list.find((e) => e.version === select.value);
      if (entry) apply(entry, data.latest);
    });
  })
  .catch(() => {
    // Leave the button on manifest.json, which build-site.sh always writes as
    // a copy of the latest release's manifest, so installing still works.
    select.textContent = '';
    const opt = document.createElement('option');
    opt.textContent = 'latest';
    select.append(opt);
    select.disabled = true;
  });
